# Generated by Django 4.1.3 on 2022-11-16 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MiApp', '0002_contacto_post_delete_familia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contacto',
            name='consulta',
            field=models.CharField(max_length=450),
        ),
        migrations.AlterField(
            model_name='contacto',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='contacto',
            name='nombre',
            field=models.CharField(max_length=100),
        ),
    ]
